# This plugin is made by TrustHage (Mick Camps)

# Prices are in levels

# Building Blocks:
# Page 1:
STONE(0): 1
STONE(1): 1
STONE(2): 1
STONE(3): 1
STONE(4): 1
STONE(5): 1
STONE(6): 1
GRASS(0): 1
DIRT(0): 1
DIRT(1): 1
DIRT(2): 1
COBBLESTONE(0): 1
GENERIC WOOD(0): 1
REDWOOD WOOD(1): 1
BIRCH WOOD(2): 1
JUNGLE WOOD(3): 1
ACACIA WOOD(4): 1
DARK_OAK WOOD(5): 1
SAND(0): 1
SAND(1): 1
GRAVEL(0): 1
GOLD_ORE(0): 1
IRON_ORE(0): 1
COAL_ORE(0): 1
GENERIC UP GENERIC LOG(0): 1
REDWOOD UP REDWOOD LOG(1): 1
BIRCH UP BIRCH LOG(2): 1
JUNGLE UP JUNGLE LOG(3): 1
SPONGE(0): 1
SPONGE(1): 1
GLASS(0): 1
LAPIS_ORE(0): 1
LAPIS_BLOCK(0): 1
SANDSTONE(0): 1
SANDSTONE(2): 1
SANDSTONE(3): 1

# Page 2:
