package me.trusthage.menus.buy.decoration;

import org.bukkit.Bukkit;
import org.bukkit.ChatColor;
import org.bukkit.Material;
import org.bukkit.entity.Player;
import org.bukkit.inventory.Inventory;
import org.bukkit.inventory.ItemStack;
import org.bukkit.inventory.meta.ItemMeta;

public class DecorP2 
{

	public void openDecorBuyP2(Player player){
		
		Inventory decorp2 = Bukkit.createInventory(null, 54, "Decoration Blocks         Page: 2");
		
		ItemStack vines = new ItemStack(Material.VINE);
		ItemMeta vinesMeta = vines.getItemMeta();
		ItemStack lilypad = new ItemStack(Material.WATER_LILY);
		ItemMeta lilypadMeta = lilypad.getItemMeta();
		ItemStack netherfence = new ItemStack(Material.NETHER_FENCE);
		ItemMeta netherfenceMeta = netherfence.getItemMeta();
		ItemStack enchanttable = new ItemStack(Material.ENCHANTMENT_TABLE);
		ItemMeta enchanttableMeta = enchanttable.getItemMeta();
		ItemStack endportal = new ItemStack(Material.ENDER_PORTAL_FRAME);
		ItemMeta endportalMeta = endportal.getItemMeta();
		ItemStack endchest = new ItemStack(Material.ENDER_CHEST);
		ItemMeta endchestMeta = endchest.getItemMeta();
		ItemStack anvil = new ItemStack(Material.ANVIL);
		ItemMeta anvilMeta = anvil.getItemMeta();
		ItemStack pane = new ItemStack(Material.THIN_GLASS);
		ItemMeta paneMeta = pane.getItemMeta();
		ItemStack whitepane = new ItemStack(Material.STAINED_GLASS_PANE);
		ItemMeta whitepaneMeta = whitepane.getItemMeta();
		ItemStack orangepane = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)1);
		ItemMeta orangepaneMeta = orangepane.getItemMeta();
		ItemStack magentapane = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)2);
		ItemMeta magentapaneMeta = magentapane.getItemMeta();
		ItemStack lbluepane = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)3);
		ItemMeta lbluepaneMeta = lbluepane.getItemMeta();
		ItemStack yellowpane = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)4);
		ItemMeta yellowpaneMeta = yellowpane.getItemMeta();
		ItemStack limepane = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)5);
		ItemMeta limepaneMeta = limepane.getItemMeta();
		ItemStack pinkpane = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)6);
		ItemMeta pinkpaneMeta = pinkpane.getItemMeta();
		ItemStack graypane = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)7);
		ItemMeta graypaneMeta = graypane.getItemMeta();
		ItemStack lgraypane = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)8);
		ItemMeta lgraypaneMeta = lgraypane.getItemMeta();
		ItemStack cyanpane = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)9);
		ItemMeta cyanpaneMeta = cyanpane.getItemMeta();
		ItemStack purplepane = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)10);
		ItemMeta purplepaneMeta = purplepane.getItemMeta();
		ItemStack bluepane = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)11);
		ItemMeta bluepaneMeta = bluepane.getItemMeta();
		ItemStack brownpane = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)12);
		ItemMeta brownpaneMeta = brownpane.getItemMeta();
		ItemStack greenpane = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)13);
		ItemMeta greenpaneMeta = greenpane.getItemMeta();
		ItemStack redpane = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)14);
		ItemMeta redpaneMeta = redpane.getItemMeta();
		ItemStack blackpane = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
		ItemMeta blackpaneMeta = blackpane.getItemMeta();
		ItemStack acacialeaves = new ItemStack(Material.LEAVES_2);
		ItemMeta acacialeavesMeta = acacialeaves.getItemMeta();
		ItemStack doakleaves = new ItemStack(Material.LEAVES_2, 1, (short)1);
		ItemMeta doakleavesMeta = doakleaves.getItemMeta();
		ItemStack slimeblock = new ItemStack(Material.SLIME_BLOCK);
		ItemMeta slimeblockMeta = slimeblock.getItemMeta();
		ItemStack whitecarpet = new ItemStack(Material.CARPET);
		ItemMeta whitecarpetMeta = whitecarpet.getItemMeta();
		ItemStack orangecarpet = new ItemStack(Material.CARPET, 1, (short)1);
		ItemMeta orangecarpetMeta = orangecarpet.getItemMeta();
		ItemStack magentacarpet = new ItemStack(Material.CARPET, 1, (short)2);
		ItemMeta magentacarpetMeta = magentacarpet.getItemMeta(); 
		ItemStack lbluecarpet = new ItemStack(Material.CARPET, 1, (short)3);
		ItemMeta lbluecarpetMeta = lbluecarpet.getItemMeta(); 
		ItemStack yellowcarpet = new ItemStack(Material.CARPET, 1, (short)4);
		ItemMeta yellowcarpetMeta = yellowcarpet.getItemMeta(); 
		ItemStack limecarpet = new ItemStack(Material.CARPET, 1, (short)5);
		ItemMeta limecarpetMeta = limecarpet.getItemMeta(); 
		ItemStack pinkcarpet = new ItemStack(Material.CARPET, 1, (short)6);
		ItemMeta pinkcarpetMeta = pinkcarpet.getItemMeta(); 
		ItemStack graycarpet = new ItemStack(Material.CARPET, 1, (short)7);
		ItemMeta graycarpetMeta = graycarpet.getItemMeta(); 
		ItemStack lgraycarpet = new ItemStack(Material.CARPET, 1, (short)8);
		ItemMeta lgraycarpetMeta = lgraycarpet.getItemMeta(); 
		ItemStack back = new ItemStack(Material.BARRIER);
		ItemMeta backMeta = back.getItemMeta();
		ItemStack nextpage = new ItemStack(Material.ENDER_PEARL);
		ItemMeta nextpageMeta = nextpage.getItemMeta();
		ItemStack line = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15);
		ItemMeta lineMeta = line.getItemMeta();
		ItemStack previouspage = new ItemStack(Material.ENDER_PEARL);
		ItemMeta previouspageMeta = previouspage.getItemMeta();

		vinesMeta.setDisplayName("Vines 16x:");	
		vines.setItemMeta(vinesMeta);
		lilypadMeta.setDisplayName("Lily Pad 16x:");	
		lilypad.setItemMeta(lilypadMeta);
		netherfenceMeta.setDisplayName("Nether Brick Fence 16x:");
		netherfence.setItemMeta(netherfenceMeta);	
		enchanttableMeta.setDisplayName("Enchantment Table 1x:");
		enchanttable.setItemMeta(enchanttableMeta);
		endportalMeta.setDisplayName("End Portal 16x:");
		endportal.setItemMeta(endportalMeta);
		endchestMeta.setDisplayName("Ender Chest 1x:");
		endchest.setItemMeta(endchestMeta);
		anvilMeta.setDisplayName("Anvil 1x:");
		anvil.setItemMeta(anvilMeta);
		paneMeta.setDisplayName("Glass Pane 16x:");
		pane.setItemMeta(paneMeta);
		whitepaneMeta.setDisplayName("White Stained Glass Pane 16x:");
		whitepane.setItemMeta(whitepaneMeta);
		orangepaneMeta.setDisplayName("Orange Stained Glass Pane 16x:");
		orangepane.setItemMeta(orangepaneMeta);
		magentapaneMeta.setDisplayName("Magenta Stained Glass Pane 16x:");
		magentapane.setItemMeta(magentapaneMeta);
		lbluepaneMeta.setDisplayName("Light Blue Stained Glass Pane 16x:");
		lbluepane.setItemMeta(lbluepaneMeta);
		yellowpaneMeta.setDisplayName("Yellow Stained Glass Pane 16x:");
		yellowpane.setItemMeta(yellowpaneMeta);
		limepaneMeta.setDisplayName("Lime Stained Glass Pane 16x:");
		limepane.setItemMeta(limepaneMeta);
		pinkpaneMeta.setDisplayName("Pink Stained Glass Pane 16x:");
		pinkpane.setItemMeta(pinkpaneMeta);
		graypaneMeta.setDisplayName("Gray Stained Glass Pane 16x:");
		graypane.setItemMeta(graypaneMeta);
		lgraypaneMeta.setDisplayName("Light Gray Stained Glass Pane 16x:");
		lgraypane.setItemMeta(lgraypaneMeta);
		cyanpaneMeta.setDisplayName("Cyan Stained Glass Pane 16x:");
		cyanpane.setItemMeta(cyanpaneMeta);
		purplepaneMeta.setDisplayName("Purple Stained Glass Pane 16x:");
		purplepane.setItemMeta(purplepaneMeta);
		bluepaneMeta.setDisplayName("Blue Stained Glass Pane 16x:");
		bluepane.setItemMeta(bluepaneMeta);
		brownpaneMeta.setDisplayName("Brown Stained Glass Pane 16x:");
		brownpane.setItemMeta(brownpaneMeta);
		greenpaneMeta.setDisplayName("Green Stained Glass Pane 16x:");
		greenpane.setItemMeta(greenpaneMeta);
		redpaneMeta.setDisplayName("Red Stained Glass Pane 16x:");
		redpane.setItemMeta(redpaneMeta);
		blackpaneMeta.setDisplayName("Black Stained Glass Pane 16x:");
		blackpane.setItemMeta(blackpaneMeta);
		acacialeavesMeta.setDisplayName("Acacia Leaves 16x:");
		acacialeaves.setItemMeta(acacialeavesMeta);
		doakleavesMeta.setDisplayName("Dark Oak Leaves 16x:");
		doakleaves.setItemMeta(doakleavesMeta);
		slimeblockMeta.setDisplayName("Slime Block 16x:");
		slimeblock.setItemMeta(slimeblockMeta);
		whitecarpetMeta.setDisplayName("Carpet 16x:");
		whitecarpet.setItemMeta(whitecarpetMeta);
		orangecarpetMeta.setDisplayName("Orange Carpet 16x:");
		orangecarpet.setItemMeta(orangecarpetMeta);
		magentacarpetMeta.setDisplayName("Magenta Carpet 16x:");
		magentacarpet.setItemMeta(magentacarpetMeta);
		lbluecarpetMeta.setDisplayName("Light Blue Carpet 16x:");
		lbluecarpet.setItemMeta(lbluecarpetMeta);
		yellowcarpetMeta.setDisplayName("Yellow Carpet 16x:");
		yellowcarpet.setItemMeta(yellowcarpetMeta);
		limecarpetMeta.setDisplayName("Lime Carpet 16x:");
		limecarpet.setItemMeta(limecarpetMeta);
		pinkcarpetMeta.setDisplayName("Pink Carpet 16x:");
		pinkcarpet.setItemMeta(pinkcarpetMeta);
		graycarpetMeta.setDisplayName("Gray Carpet 16x:");
		graycarpet.setItemMeta(graycarpetMeta);
		lgraycarpetMeta.setDisplayName("Light Gray Carpet 16x:");
		lgraycarpet.setItemMeta(lgraycarpetMeta);
		backMeta.setDisplayName(ChatColor.RED + "Back");
		back.setItemMeta(backMeta);
		nextpageMeta.setDisplayName("Next Page");
		nextpage.setItemMeta(nextpageMeta);
		lineMeta.setDisplayName("-");
		line.setItemMeta(lineMeta);
		previouspageMeta.setDisplayName("Previous Page");
		previouspage.setItemMeta(previouspageMeta);

		decorp2.setItem(0, vines);
		decorp2.setItem(1, lilypad);
		decorp2.setItem(2, netherfence);
		decorp2.setItem(3, enchanttable);
		decorp2.setItem(4, endportal);
		decorp2.setItem(5, endchest);
		decorp2.setItem(6, anvil);
		decorp2.setItem(7, pane);
		decorp2.setItem(8, whitepane);
		decorp2.setItem(9, orangepane);
		decorp2.setItem(10, magentapane);
		decorp2.setItem(11, lbluepane);
		decorp2.setItem(12, yellowpane);
		decorp2.setItem(13, limepane);
		decorp2.setItem(14, pinkpane);
		decorp2.setItem(15, graypane);
		decorp2.setItem(16, lgraypane);
		decorp2.setItem(17, cyanpane);
		decorp2.setItem(18, purplepane);
		decorp2.setItem(19, bluepane);
		decorp2.setItem(20, brownpane);
		decorp2.setItem(21, greenpane);
		decorp2.setItem(22, redpane);
		decorp2.setItem(23, blackpane);
		decorp2.setItem(24, acacialeaves);
		decorp2.setItem(25, doakleaves);
		decorp2.setItem(26, slimeblock);
		decorp2.setItem(27, whitecarpet);
		decorp2.setItem(28, orangecarpet);
		decorp2.setItem(29, magentacarpet);
		decorp2.setItem(30, lbluecarpet);
		decorp2.setItem(31, yellowcarpet);
		decorp2.setItem(32, limecarpet);
		decorp2.setItem(33, pinkcarpet);
		decorp2.setItem(34, graycarpet);
		decorp2.setItem(35, lgraycarpet);
		decorp2.setItem(36, line);
		decorp2.setItem(37, line);
		decorp2.setItem(38, line);
		decorp2.setItem(39, line);
		decorp2.setItem(40, line);
		decorp2.setItem(41, line);
		decorp2.setItem(42, line);
		decorp2.setItem(43, line);
		decorp2.setItem(44, line);
		decorp2.setItem(49, back);
		decorp2.setItem(53, nextpage);
		decorp2.setItem(45, previouspage);
		
		player.openInventory(decorp2);
	}
	
}
